SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") as REVIEW_DATE
FROM MEMBER_PROFILE mp
         JOIN REST_REVIEW rr ON mp.MEMBER_ID = rr.MEMBER_ID
WHERE mp.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
    )
ORDER BY REVIEW_DATE , REVIEW_TEXT;

-- JOIN을 쓸 땐 서브쿼리를 안써야되는 줄만 알았다;