SELECT ri.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) as REVIEW_AVG_SCORE
FROM REST_INFO ri
         JOIN REST_REVIEW rr ON ri.REST_ID = rr.REST_ID
WHERE ADDRESS like "서울%"
GROUP BY ri.REST_ID
ORDER BY REVIEW_AVG_SCORE DESC, FAVORITES DESC;

-- ROUND 반올림 함수, AVG 평균 함수